### ISSUE TITLE
monetary.formatted_money() and monetary.money() looks like mixed.

### ISSUE THREAD

**Issue by kamyanskiy** [pilosus/ForgeryPy3#2]
From documentation is expected:
```
forgery_py.monetary.formatted_money()  '$5.49'

forgery_py.monetary.money()  '9.20'
```

But actually these methods returns:

```
In [11]: forgery_py.monetary.formatted_money()
Out[11]: '3.50'

In [10]: forgery_py.monetary.money()
Out[10]: '$0.90'

```
So I have feeling that something wrong - documentation or methods were mixed accidentally ) Seems that is documentation issue.

**Comment by pilosus** [comment]
Good catch! In fact documentation is okay, but methods, docstings and tests are indeed mixed up. 
Are you going to fix that with your Pull Request?

**Comment by kamyanskiy** [comment]
@pilosus  sure, I pushed one https://github.com/pilosus/ForgeryPy3/pull/3
